name: CI for Develop

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: HTMLHint Linter
        uses: reviewdog/action-htmlhint@v1
        with:
          reporter: github-check
          fail_on_error: true
          htmlhint_flags: .

      - name: Stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-check
          fail_on_error: true
